import { ResourceProps } from "@refinedev/core";
import {
  Users, Package, CalendarCheck, CreditCard, LayoutDashboard, Settings,
  MapPin, UserCircle, FileText, BookOpen, Headphones, History, ScrollText, BarChart3,
  UserPlus,
  Target,
  CalendarClock,
  Gauge,
} from "lucide-react";

export const resources: ResourceProps[] = [
  {
    name: "dashboard",
    list: "/dashboard",
    meta: { label: "Dashboard", labelKey: "nav.dashboard", icon: <LayoutDashboard className="h-4 w-4" /> },
  },
  {
    name: "crm-dashboard",
    list: "/crm/dashboard",
    meta: {
      label: "CRM Dashboard",
      labelKey: "nav.crmDashboard",
      parent: "crm",
      icon: <BarChart3 className="h-4 w-4" />,
    },
  },
  {
    name: "crm-operations",
    list: "/crm/operations",
    meta: {
      label: "Operations",
      labelKey: "nav.crmOperations",
      parent: "crm",
      icon: <Gauge className="h-4 w-4" />,
    },
  },
  {
    name: "crm-sales-insights",
    list: "/crm/sales-insights",
    meta: {
      label: "Sales Insights",
      labelKey: "nav.salesInsights",
      parent: "crm",
      icon: <BarChart3 className="h-4 w-4" />,
    },
  },
  {
    name: "crm-operations-insights",
    list: "/crm/operations-insights",
    meta: {
      label: "Operations Insights",
      labelKey: "nav.operationsInsights",
      parent: "crm",
      icon: <Gauge className="h-4 w-4" />,
    },
  },
  {
    name: "ai-operations",
    list: "/ai/operations",
    meta: {
      label: "Operations Assistant",
      labelKey: "nav.operationsAgent",
      icon: <CalendarCheck className="h-4 w-4" />,
    },
  },
  {
    name: "ai-sales",
    list: "/ai/sales",
    meta: {
      label: "Sales Assistant",
      labelKey: "nav.salesAgent",
      icon: <Target className="h-4 w-4" />,
    },
  },
  {
    name: "leads",
    list: "/crm/leads",
    create: "/crm/leads/create",
    edit: "/crm/leads/edit/:id",
    show: "/crm/leads/show/:id",
    meta: {
      label: "Leads",
      labelKey: "nav.leads",
      parent: "crm",
      icon: <UserPlus className="h-4 w-4" />,
    },
  },
  {
    name: "opportunities",
    list: "/crm/opportunities",
    create: "/crm/opportunities/create",
    edit: "/crm/opportunities/edit/:id",
    show: "/crm/opportunities/show/:id",
    meta: {
      label: "Opportunities",
      labelKey: "nav.opportunities",
      parent: "crm",
      icon: <Target className="h-4 w-4" />,
    },
  },
  {
    name: "quotations",
    list: "/crm/quotations",
    create: "/crm/quotations/create",
    edit: "/crm/quotations/edit/:id",
    show: "/crm/quotations/show/:id",
    meta: {
      label: "Quotations",
      labelKey: "nav.quotations",
      parent: "crm",
      icon: <FileText className="h-4 w-4" />,
    },
  },
  {
    name: "activities",
    list: "/crm/activities",
    create: "/crm/activities/create",
    edit: "/crm/activities/edit/:id",
    show: "/crm/activities/show/:id",
    meta: {
      label: "Activities",
      labelKey: "nav.activities",
      parent: "crm",
      icon: <CalendarClock className="h-4 w-4" />,
    },
  },
  {
    name: "customers",
    list: "/customers",
    create: "/customers/create",
    edit: "/customers/edit/:id",
    show: "/customers/show/:id",
    meta: { label: "Customers", labelKey: "nav.customers", icon: <Users className="h-4 w-4" /> },
  },
  {
    name: "travelers",
    list: "/travelers",
    create: "/travelers/create",
    edit: "/travelers/edit/:id",
    show: "/travelers/show/:id",
    meta: { label: "Travelers", labelKey: "nav.travelers", icon: <UserCircle className="h-4 w-4" /> },
  },
  {
    name: "destinations",
    list: "/destinations",
    create: "/destinations/create",
    edit: "/destinations/edit/:id",
    show: "/destinations/show/:id",
    meta: { label: "Destinations", labelKey: "nav.destinations", icon: <MapPin className="h-4 w-4" /> },
  },
  {
    name: "packages",
    list: "/packages",
    create: "/packages/create",
    edit: "/packages/edit/:id",
    show: "/packages/show/:id",
    meta: { label: "Packages", labelKey: "nav.packages", icon: <Package className="h-4 w-4" /> },
  },
  {
    name: "bookings",
    list: "/bookings",
    create: "/bookings/create",
    edit: "/bookings/edit/:id",
    show: "/bookings/show/:id",
    meta: { label: "Bookings", labelKey: "nav.bookings", icon: <CalendarCheck className="h-4 w-4" /> },
  },
  {
    name: "invoices",
    list: "/invoices",
    create: "/invoices/create",
    edit: "/invoices/edit/:id",
    show: "/invoices/show/:id",
    meta: { label: "Invoices", labelKey: "nav.invoices", icon: <FileText className="h-4 w-4" /> },
  },
  {
    name: "payments",
    list: "/payments",
    create: "/payments/create",
    show: "/payments/show/:id",
    meta: { label: "Payments", labelKey: "nav.payments", icon: <CreditCard className="h-4 w-4" /> },
  },
  {
    name: "users",
    list: "/users",
    create: "/users/create",
    show: "/users/show/:id",
    meta: { label: "Users", labelKey: "nav.users", icon: <Users className="h-4 w-4" /> },
  },
  {
    name: "ai-knowledge",
    list: "/ai/knowledge",
    meta: {
      label: "Knowledge Agent",
      labelKey: "nav.knowledgeAgent",
      icon: <BookOpen className="h-4 w-4" />,
    },
  },
  {
    name: "ai-support",
    list: "/ai/support",
    meta: {
      label: "Support Agent",
      labelKey: "nav.supportAgent",
      icon: <Headphones className="h-4 w-4" />,
    },
  },
  {
    name: "ai-booking",
    list: "/ai/booking",
    meta: {
      label: "Booking Agent",
      labelKey: "nav.bookingAgent",
      icon: <CalendarCheck className="h-4 w-4" />,
    },
  },
  {
    name: "ai-conversations",
    list: "/ai/history",
    meta: {
      label: "AI History",
      labelKey: "nav.aiHistory",
      icon: <History className="h-4 w-4" />,
    },
  },
  {
    name: "ai-analytics",
    list: "/ai/analytics",
    meta: {
      label: "AI Analytics",
      labelKey: "nav.aiAnalytics",
      icon: <BarChart3 className="h-4 w-4" />,
    },
  },
  {
    name: "audit_logs",
    list: "/audit-logs",
    meta: {
      label: "Audit Log",
      labelKey: "nav.auditLogs",
      icon: <ScrollText className="h-4 w-4" />,
    },
  },
  {
    name: "settings",
    list: "/settings",
    meta: { label: "Settings", labelKey: "nav.settings", icon: <Settings className="h-4 w-4" /> },
  },
];
