import { DOMAIN_EVENT_TYPE } from "@/lib/events/types";

/** Domain events that trigger async score recomputation (Sprint 9C). */
export const SALES_SCORE_EVENT_TYPES = new Set<string>([
  DOMAIN_EVENT_TYPE.QUOTATION_ACCEPTED,
  DOMAIN_EVENT_TYPE.QUOTATION_REJECTED,
  DOMAIN_EVENT_TYPE.QUOTATION_SENT,
  DOMAIN_EVENT_TYPE.QUOTATION_VIEWED,
  DOMAIN_EVENT_TYPE.BOOKING_CREATED,
  DOMAIN_EVENT_TYPE.BOOKING_UPDATED,
  DOMAIN_EVENT_TYPE.BOOKING_CANCELLED,
  DOMAIN_EVENT_TYPE.PAYMENT_CREATED,
  DOMAIN_EVENT_TYPE.PAYMENT_AUTHORIZED,
  DOMAIN_EVENT_TYPE.PAYMENT_COMPLETED,
  DOMAIN_EVENT_TYPE.PAYMENT_FAILED,
  DOMAIN_EVENT_TYPE.CUSTOMER_PORTAL_REGISTERED,
]);

export function shouldEnqueueSalesScore(eventType: string): boolean {
  return SALES_SCORE_EVENT_TYPES.has(eventType);
}
